import OpenAPIRuntime
import Wire

// The handler collation feature: the contributor protocol and its collation key.

/// A transport contributor. `registerWireHandlers` is generated by `@OpenAPIController`
/// — it owns the mount (an optional base path) and delegates to the generated
/// `registerHandlers(on:)`. Not intended to be written by hand (the `Wire` in the name
/// marks it generated).
public protocol TransportContributor {
    func registerWireHandlers(on transport: any ServerTransport) throws
}

/// The collation keys namespace; each feature adds its key by extension. Named for the
/// cross-runtime surface (`Transport`), not the package, so M5's WireMVC controllers fold
/// into the same key rather than declaring a parallel one.
public enum TransportKeys {}

extension TransportKeys {
    /// Handlers `@OpenAPIController` aliases into.
    public static let handlers = CollectedKey<any TransportContributor>()
}
